waypoint_navigation:
  waypoint_navigation_node:
    ros__parameters:
      wps:
        - "wp0"
        - "4.0"
        - "10.0"
        - "0.025"
        - "0.0"

        - "wp1"
        - "-8.82"
        - "-20.2"
        - "0.025"
        - "0.0"

        - "wp2"
        - "-8.13"
        - "-5.19"
        - "0.025"
        - "1.0"

        - "wp3"
        - "4.05"
        - "-27.55"
        - "0.025"
        - "0.9"

        - "wp4"
        - "8.23"
        - "-21.23"
        - "0.025"
        - "0.9"

        - "wp5"
        - "7.85"
        - "-6.81"
        - "0.0025"
        - "0.9"
